### ISSUE TITLE
Update reference for "Anon18"

### ISSUE THREAD

**Issue by cjpatton** [tlswg/tls13-rfc#3]
Hey @ekr, before you publish, I need to send you an update for this reference. The title has changed, and I'll have an eprint link for you. This should happen Tuesday (6/26) or Wednesday (6/27) next week.

**Comment by lbartholomew-rpc** [comment]
This item was updated (OLD was [Anon18]; NEW is [PS18]).  Reflected in the commit made by Ekr 4 days ago ("Second pass from RFC Ed").
